language: node_js
node_js: lts/*
jobs:
  include:
    - stage: DEPLOY
      script: './createBuild.sh'
      deploy:
        app: find-recipes-app
        api_key:
          secure: SqAd4pp96EoOHlb32lhmOLoaVTKNjw8ve3C5CuOKifgifbco2TY+Cj6VBuqgZyCa5vI9mnAXXMd4ZQ1Td/StAN7jsCHjqFLBzwOh4L6yLZZ53EHaT7s27jkHJVXCSMv0wQTYOAUPoeLI1m1NQD9DLzTJOSBoamsLpm/Fai6AQbX5ehLH5+c4vKVAr21f4fEFIxR6coEILkapGb8OGJCaMqDr/ZqvEefsz312rpCXVaCkzoXpfBeyBi7MHaeD0BlO9s9pBeP56CtULYV7YjT37ok5+ibGlk392rq/AhtxhPkg/qOuQm+2yVwQ/pqQQ+1uf7XrFAue6G3gRBt23Yd0SWtE8OECrGfXfkxs3jwKcKOu0O4k6ci5LWbv3zk5+WnkUBNvQYyXcUqNTTzBJHs3CJnhbCYB4oLgWItUt/w8pgKEHoEyPYjCeTiE1Hu0gURE4K4y2mrozGdH7JRZW6pOtogI9naTcyle4nsGSm20mRXdaE2OmW+rMT/tVLieVhgDAsCB6FE8WPR9Y0dH/mLkkWKgrNmF/zrj9dOsXVSZqe7/+tDCZ9y0mWtKuDN6bMrRhtiPMqneuiFbh6uggvwo1qAFo/UvJRJySrHl6Gh8Tdgv6n3V48Jv8MsEx0D1MC1Ply/QClWUI9vO0RhsM1F+rTfB4YV3ANBwED4Y2syGg1U=
        provider: heroku
        run: restart
        skip_cleanup: true
