language: node_js
node_js: lts/*
jobs:
  include:
    - stage: DEPLOY
      script: './createBuild.sh'
      deploy:
        app: find-recipes-app
        api_key:
          secure: RmJvHC3SJFQgzU4uvD6J7bntGB1Jt6k/ZnJFKy2ZWdC/AWbcpG1M06UEZHmLdONcS9HJdwxj7z6R+q2Nfd8TwY3xfYcEDFQ5jFhn23r7/zMCMF2ZdToQUg9lL9d4LnnHpdiqfXlr5ULlnOARL1FhXtpOhgPtthbkDeQcsDPo3cGsa0tmVPkf7mzTIduDHgB3VgqmKKVzvVihVDXTBaeEXw9UmxUP1dThxSmmdHN/Rrb//EPZs6m3Y9XAkYYw+Tc2JfoNlU4K8Tk2TZxjCORkQcdSSs8O5OSmQkb4ir4b7M1nHRQwYaAhhkrjhw1QcGEA60BwX16VMobQJqOqVlB0sPwDuAFxWWjlyY5NPE62s57vWN7in2DevKfLOTVJ/Oxbw8UFRVilKMOIDP7BZIExIOsCvQmVmRiN477giRdrsd97C/oo6oN94U9dGkUemE5ilVeGo5zH77WzJ7IjdzQbFq9AdcK+ZzlXFGdBXHktt3F+7RC4eTUAwASr+LHdZzV0xSuovKdjvh8Y8ahBcy1iggjT2y7T4ltqE0AVWnF4Ag2lDjpni69tGlKXwDwCIpW8v89a0CUBjRctF+oZQ+2EQ1VhBNFXy5olyXo4jVy5uFQbKyv04OqAD5AzUcK7zgMo99mBuEfA9RlxsEHFXTeCtPIL3uwuN/+EtvxO18ZJyLI=
        provider: heroku
        run: restart
        skip_cleanup: true
